SELECT DATABASE_NAME, CALENDAR_YEAR, FISHERY_SECTOR, GEAR, GEAR_SUBTYPE, 
	LANDED_ROUND_KG, TOTAL_RELEASED_ROUND_KG, TOTAL_RELEASED_COUNT, TOTAL_KG
FROM (
	SELECT 'PacHarvSable' AS DATABASE_NAME, 
		YEAR(D.OFFLOAD_DT) AS CALENDAR_YEAR, 'SABLEFISH' AS FISHERY_SECTOR, GEAR, GEAR AS GEAR_SUBTYPE, SPECIES_CODE,
		SUM(ISNULL(LANDED, 0)) AS LANDED_ROUND_KG,
		SUM(ISNULL(DISCARDED, 0)) AS TOTAL_RELEASED_ROUND_KG,
		NULL AS TOTAL_RELEASED_COUNT,
		SUM(ISNULL(LANDED, 0)+ISNULL(DISCARDED, 0)) AS TOTAL_KG
	FROM PacHarvSable.dbo.D_Official_Catch D
	WHERE OFFLOAD_DT > '2001-07-31 00:00:00' AND SPECIES_CODE = '044' AND ISNULL(MAJOR_STAT_AREA_CDE,0) != 1
		AND ISNULL(D.DFO_MGMT_AREA_CDE,0) != '12'
	GROUP BY YEAR(D.OFFLOAD_DT), GEAR, SPECIES_CODE

	UNION ALL

	SELECT 'PacHarHL' AS DATABASE_NAME, D.Calendar_Year AS CALENDAR_YEAR,
		FISHERY AS FISHERY_SECTOR, 
		CASE 
			WHEN GEAR_TYPE_NME = 'LONGLINE' THEN 'LONGLINE'
			WHEN GEAR_TYPE_NME IN ('HANDLINE', 'ROD AND REEL', 'TROLL') THEN 'HOOK AND LINE'
			ELSE 'LONGLINE OR HOOK AND LINE' END AS GEAR,
		CASE WHEN G.GEAR_TYPE_NME = 'UNKNOWN' THEN 'UNSPECIFIED' ELSE G.GEAR_TYPE_NME END AS GEAR_SUBTYPE,
		SPECIES_CODE, 
		SUM(ISNULL([LANDED/RETAINED],0)) AS LANDED_ROUND_KG,
		SUM(ISNULL(DISCARDED,0)) AS TOTAL_RELEASED_ROUND_KG,
		SUM(ISNULL(RELEASED_COUNT,0)) AS TOTAL_RELEASED_COUNT,
		SUM(ISNULL([LANDED/RETAINED],0)+ISNULL(DISCARDED,0)) AS TOTAL_KG
	FROM PacHarvHL.dbo.D_Official_Catch D
	LEFT JOIN (
		SELECT C.OBFL_HAIL_IN_NO, OBFL_SET_NO, OBFL_SPECIES_CDE, 
			SUM(ISNULL(OBFL_EST_WEIGHT,0)) AS RELEASED_KG, 
			SUM(ISNULL(OBFL_EST_COUNT,0)) AS RELEASED_COUNT
		FROM PacHarvHL.dbo.B4_Catches C
		INNER JOIN PacHarvHL.dbo.C_Catch_Utilization U ON U.CATCH_UTILIZATION_CDE = C.OBFL_CATCH_UTILIZATION_CDE
		WHERE CATCH_UTILIZATION_DISCARD_IND = 1 AND ISNULL(OBFL_EST_WEIGHT,0)+ISNULL(OBFL_EST_COUNT,0)>0
		GROUP BY C.OBFL_HAIL_IN_NO, OBFL_SET_NO, OBFL_SPECIES_CDE
		) REL ON REL.OBFL_HAIL_IN_NO = D.HAIL_IN_NO AND REL.OBFL_SET_NO = D.SET_NO 
			AND REL.OBFL_SPECIES_CDE = D.SPECIES_CODE
	INNER JOIN PacHarvHL.dbo.C_Gear_Type G ON G.GEAR_TYPE_CDE = D.GEAR_TYPE_CDE
	WHERE D.OFFLOAD_DATE < '04/01/2006' AND -- cutoff for PHL data
		SPECIES_CODE = '044' AND Fishing_Year > 2000 AND ISNULL(MAJOR_STAT_AREA,0) != 1
		AND ISNULL(D.DFO_MGMT_AREA_CDE,0)!= '12'
	GROUP BY D.Calendar_Year, FISHERY,
		CASE WHEN GEAR_TYPE_NME = 'LONGLINE' THEN 'LONGLINE'
			WHEN GEAR_TYPE_NME IN ('HANDLINE', 'ROD AND REEL', 'TROLL') THEN 'HOOK AND LINE'
			ELSE 'LONGLINE OR HOOK AND LINE' END,
		CASE WHEN G.GEAR_TYPE_NME = 'UNKNOWN' THEN 'UNSPECIFIED' ELSE G.GEAR_TYPE_NME END, 
		SPECIES_CODE

	UNION ALL

	SELECT 'GFFOS' AS DATABASE_NAME, 
		YEAR(BEST_DATE) AS CALENDAR_YEAR, C.FISHERY_SECTOR, C.GEAR, GEAR_SUBTYPE, SPECIES_CODE,
		SUM(ISNULL(LANDED_ROUND_KG, 0)) AS LANDED_ROUND_KG, 
		NULL AS TOTAL_RELEASED_ROUND_KG, 
		SUM(ISNULL(TOTAL_RELEASED_COUNT, 0)) AS TOTAL_RELEASED_COUNT,
		NULL AS TOTAL_KG
	FROM GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH C
	LEFT JOIN GFDataReq.dbo.GF_FISHING_YEAR_VW FY ON FY.FOS_TRIP_ID = C.TRIP_ID
	LEFT JOIN (
		SELECT TRIP_ID
		FROM (
		-- Identify trips that are also in PacHarvHL
		SELECT DISTINCT CAST(H.TRIP_ID AS VARCHAR(50)) AS TRIP_ID FROM GFFOS.dbo.GF_HAIL_NUMBER H
		INNER JOIN PacHarvHL.dbo.D_Official_Catch C ON H.HAIL_NUMBER = C.HAIL_IN_NO
		WHERE H.HAIL_TYPE = 'IN' AND OFFLOAD_DATE < '04/01/2006' -- up to cutoff for PHL
		UNION ALL
		-- Identify trips that are also in PacHarvSable
		SELECT DISTINCT CAST(H.TRIP_ID AS VARCHAR(50)) AS TRIP_ID FROM GFFOS.dbo.GF_HAIL_NUMBER H
		INNER JOIN PacHarvSable.dbo.D_Official_Catch C ON H.HAIL_NUMBER = C.HAIL_IN_NO
		WHERE H.HAIL_TYPE = 'IN'
		) H
		GROUP BY TRIP_ID
		) OL ON OL.TRIP_ID = C.TRIP_ID
	WHERE OL.TRIP_ID IS NULL AND FISHERY_SECTOR != 'GROUNDFISH TRAWL' AND FISHERY_SECTOR != 'ROCKFISH INSIDE' AND 
		YEAR(C.BEST_DATE) > 2004 AND SPECIES_CODE = '044' AND ISNULL(MAJOR_STAT_AREA_CODE,'00') != '01'
		AND ISNULL(DFO_STAT_AREA_CODE,0)!= 12
	GROUP BY YEAR(BEST_DATE), C.FISHERY_SECTOR, C.GEAR, C.GEAR_SUBTYPE, SPECIES_CODE
) C
	ORDER BY FISHERY_SECTOR, CALENDAR_YEAR

