SELECT DATABASE_NAME, CALENDAR_YEAR, FISHERY_SECTOR, GEAR, GEAR_SUBTYPE, 
	SUM(LANDED_ROUND_KG) AS LANDED_ROUND_KG, 
	SUM(TOTAL_RELEASED_ROUND_KG) AS TOTAL_RELEASED_ROUND_KG, 
	SUM(TOTAL_KG) AS TOTAL_KG
FROM (
	SELECT 'PacHarvest' AS DATABASE_NAME, 
		CALENDAR_YEAR, 'GROUNDFISH TRAWL' AS FISHERY_SECTOR, C.GEAR, C.GEAR_SUBTYPE, SPECIES_CODE,
		SUM(ISNULL(LANDED, 0)) AS LANDED_ROUND_KG, 
		SUM(ISNULL(DISCARDED, 0)) AS TOTAL_RELEASED_ROUND_KG, 
		SUM(ISNULL(LANDED, 0) + ISNULL(DISCARDED, 0)) AS TOTAL_KG
	FROM (
		SELECT D.HAIL_IN_NO, YEAR(D.OFFLOAD_DATE) AS CALENDAR_YEAR, D.SET_NO, D.SPECIES_CODE, 'TRAWL' AS GEAR, 
			CASE
				WHEN GS.GEAR_SUBTYPE_NME = 'STANDARD BOTTOM TRAWL' THEN 'BOTTOM TRAWL'
				WHEN GS.GEAR_SUBTYPE_NME = 'UNKNOWN TRAWL' THEN 'UNSPECIFIED'
				ELSE GS.GEAR_SUBTYPE_NME END AS GEAR_SUBTYPE,
			MAJOR_STAT_AREA, 
			LANDED, DISCARDED
		FROM PacHarvest.dbo.D_Official_Catch D
		INNER JOIN PacHarvest.dbo.C_Gear_Subtype GS ON 
			GS.GEAR_TYPE_CDE = D.GEAR_TYPE_CDE AND GS.GEAR_SUBTYPE_CDE = D.GEAR_SUBTYPE_CDE
		WHERE D.SPECIES_CODE = '044' AND ISNULL(MAJOR_STAT_AREA,'00') != '01' 
			AND ISNULL(DFO_MGMT_AREA_CDE,0) != 12
	) C
	GROUP BY CALENDAR_YEAR, C.GEAR, C.GEAR_SUBTYPE, SPECIES_CODE

	UNION ALL

	SELECT 'GFFOS' AS DATABASE_NAME, 
		YEAR(C.BEST_DATE) AS CALENDAR_YEAR, C.FISHERY_SECTOR, C.GEAR, GEAR_SUBTYPE, SPECIES_CODE,
		SUM(ISNULL(LANDED_ROUND_KG, 0)) AS LANDED_ROUND_KG, 
		SUM(ISNULL(TOTAL_RELEASED_ROUND_KG, 0)) AS TOTAL_RELEASED_ROUND_KG, 
		SUM(ISNULL(LANDED_ROUND_KG, 0)+ISNULL(TOTAL_RELEASED_ROUND_KG, 0)) AS TOTAL_KG
	FROM GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH C
	LEFT JOIN GFDataReq.dbo.GF_FISHING_YEAR_VW FY ON FY.FOS_TRIP_ID = C.TRIP_ID
	WHERE FISHERY_SECTOR = 'GROUNDFISH TRAWL' AND  
		YEAR(C.BEST_DATE) > 2005 AND SPECIES_CODE = '044' AND ISNULL(MAJOR_STAT_AREA_CODE,'00') != '01'
		AND ISNULL(DFO_STAT_AREA_CODE,0) != 12
	GROUP BY YEAR(C.BEST_DATE), C.FISHERY_SECTOR, C.GEAR, C.GEAR_SUBTYPE, SPECIES_CODE

	UNION ALL

	SELECT 'GFBio' AS DATABASE_NAME,
		YEAR(T.TRIP_START_DATE) AS CALENDAR_YEAR, 
		'GROUNDFISH TRAWL' AS FISHERY_SECTOR, 'TRAWL' AS GEAR, 'MIDWATER TRAWL' AS GEAR_SUBTYPE,
		SPECIES_CODE, 0 AS LANDED_ROUND_KG, 0 AS TOTAL_RELEASED_ROUND_KG, SUM(C.CATCH_WEIGHT) AS TOTAL_KG
	FROM GFBioSQL.dbo.TRIP T
	INNER JOIN GFBioSQL.dbo.FISHING_EVENT F ON F.TRIP_ID = T.TRIP_ID
	INNER JOIN GFBioSQL.dbo.FISHING_EVENT_CATCH FEC ON FEC.FISHING_EVENT_ID = F.FISHING_EVENT_ID
	INNER JOIN GFBioSQL.dbo.CATCH C ON C.CATCH_ID = FEC.CATCH_ID
	WHERE YEAR(T.TRIP_START_DATE) BETWEEN 1996 AND 2006 AND C.SPECIES_CODE = '044' 
		AND ISNULL(F.MAJOR_STAT_AREA_CODE,'00') != '01' AND ISNULL(F.DFO_STAT_AREA_CODE,0) != 12
		AND T.TRIP_SUB_TYPE_CODE = 5
	GROUP BY YEAR(T.TRIP_START_DATE), SPECIES_CODE
)C
GROUP BY DATABASE_NAME, CALENDAR_YEAR, FISHERY_SECTOR, GEAR, GEAR_SUBTYPE
ORDER BY CALENDAR_YEAR
