SELECT 'GFFOS' AS DATABASE_NAME, 
	FISHING_YEAR, C.FISHERY_SECTOR, C.TRIP_CATEGORY, C.GEAR, GEAR_SUBTYPE,
	SUM(ISNULL(LANDED_ROUND_KG, 0)) AS LANDED_ROUND_KG, 
	SUM(ISNULL(RETAINED_ROUND_KG, 0)) AS RETAINED_ROUND_KG, 
	SUM(ISNULL(RETAINED_COUNT, 0)) AS RETAINED_COUNT, 
	SUM(ISNULL(LANDED_COUNT, 0)) AS LANDED_COUNT, 
	SUM(ISNULL(TOTAL_RELEASED_ROUND_KG, 0)) AS TOTAL_RELEASED_ROUND_KG, 
	SUM(ISNULL(TOTAL_RELEASED_COUNT, 0)) AS TOTAL_RELEASED_COUNT,
	SUM(ISNULL(SUBLEGAL_RELEASED_ROUND_KG, 0)) AS SUBLEGAL_RELEASED_ROUND_KG, 
	SUM(ISNULL(LEGAL_RELEASED_ROUND_KG, 0)) AS LEGAL_RELEASED_ROUND_KG, 
	SUM(ISNULL(SUBLEGAL_RELEASED_COUNT, 0)) AS SUBLEGAL_RELEASED_COUNT, 
	SUM(ISNULL(LEGAL_RELEASED_COUNT, 0)) AS LEGAL_RELEASED_COUNT, 
	SUM(ISNULL(SUBLEGAL_LICED_COUNT, 0)+ISNULL(LEGAL_LICED_COUNT, 0)) AS LICED_COUNT, 
	SUM(ISNULL(SUBLEGAL_BAIT_COUNT, 0)+ISNULL(LEGAL_BAIT_COUNT, 0)) AS BAIT_COUNT
FROM GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH C
LEFT JOIN GFDataReq.dbo.GF_FISHING_YEAR_VW FY ON FY.FOS_TRIP_ID = C.TRIP_ID
LEFT JOIN (
	SELECT TRIP_ID
	FROM (
	-- Identify trips that are also in PacHarvHL
	SELECT DISTINCT CAST(H.TRIP_ID AS VARCHAR(50)) AS TRIP_ID FROM GFFOS.dbo.GF_HAIL_NUMBER H
	INNER JOIN PacHarvHL.dbo.D_Official_Catch C ON H.HAIL_NUMBER = C.HAIL_IN_NO
	WHERE H.HAIL_TYPE = 'IN' AND OFFLOAD_DATE < '04/01/2006' -- up to cutoff for PHL
	UNION ALL
	-- Identify trips that are also in PacHarvSable
	SELECT DISTINCT CAST(H.TRIP_ID AS VARCHAR(50)) AS TRIP_ID FROM GFFOS.dbo.GF_HAIL_NUMBER H
	INNER JOIN PacHarvSable.dbo.D_Official_Catch C ON H.HAIL_NUMBER = C.HAIL_IN_NO
	WHERE H.HAIL_TYPE = 'IN'
	) H
	GROUP BY TRIP_ID
	) OL ON OL.TRIP_ID = C.TRIP_ID
WHERE OL.TRIP_ID IS NULL AND SPECIES_CODE = '044' AND YEAR(C.BEST_DATE) > 2004
	AND ISNULL(MAJOR_STAT_AREA_CODE,'00') != '01' AND ISNULL(DFO_STAT_AREA_CODE,0) != 12
	/*AND FISHERY_SECTOR != 'ROCKFISH INSIDE' AND FISHERY_SECTOR ! = 'GROUNDFISH TRAWL'*/
	AND FISHERY_SECTOR = 'GROUNDFISH TRAWL'
GROUP BY FISHING_YEAR, C.FISHERY_SECTOR, C.TRIP_CATEGORY, C.GEAR, C.GEAR_SUBTYPE
ORDER BY FISHERY_SECTOR, FISHING_YEAR

SELECT 'GFFOS' AS DATABASE_NAME, YEAR(C.BEST_DATE) AS CALENDAR_YEAR, C.FISHERY_SECTOR, C.TRIP_CATEGORY, C.GEAR, C.GEAR_SUBTYPE, 
	SUM(ISNULL(LANDED_ROUND_KG, 0)) AS LANDED_ROUND_KG, 
	SUM(ISNULL(RETAINED_ROUND_KG, 0)) AS RETAINED_ROUND_KG, 
	SUM(ISNULL(RETAINED_COUNT, 0)) AS RETAINED_COUNT, 
	SUM(ISNULL(LANDED_COUNT, 0)) AS LANDED_COUNT, 
	SUM(ISNULL(TOTAL_RELEASED_ROUND_KG, 0)) AS TOTAL_RELEASED_ROUND_KG, 
	SUM(ISNULL(TOTAL_RELEASED_COUNT, 0)) AS TOTAL_RELEASED_COUNT,
	SUM(ISNULL(SUBLEGAL_RELEASED_ROUND_KG, 0)) AS SUBLEGAL_RELEASED_ROUND_KG, 
	SUM(ISNULL(LEGAL_RELEASED_ROUND_KG, 0)) AS LEGAL_RELEASED_ROUND_KG, 
	SUM(ISNULL(SUBLEGAL_RELEASED_COUNT, 0)) AS SUBLEGAL_RELEASED_COUNT, 
	SUM(ISNULL(LEGAL_RELEASED_COUNT, 0)) AS LEGAL_RELEASED_COUNT, 
	SUM(ISNULL(SUBLEGAL_LICED_COUNT, 0)+ISNULL(LEGAL_LICED_COUNT, 0)) AS LICED_COUNT, 
	SUM(ISNULL(SUBLEGAL_BAIT_COUNT, 0)+ISNULL(LEGAL_BAIT_COUNT, 0)) AS BAIT_COUNT
FROM GFFOS.dbo.GF_D_OFFICIAL_FE_CATCH C
LEFT JOIN GFDataReq.dbo.GF_FISHING_YEAR_VW FY ON FY.FOS_TRIP_ID = C.TRIP_ID
LEFT JOIN (
	SELECT TRIP_ID
	FROM (
	-- Identify trips that are also in PacHarvHL
	SELECT DISTINCT CAST(H.TRIP_ID AS VARCHAR(50)) AS TRIP_ID FROM GFFOS.dbo.GF_HAIL_NUMBER H
	INNER JOIN PacHarvHL.dbo.D_Official_Catch C ON H.HAIL_NUMBER = C.HAIL_IN_NO
	WHERE H.HAIL_TYPE = 'IN' AND OFFLOAD_DATE < '04/01/2006' -- up to cutoff for PHL
	UNION ALL
	-- Identify trips that are also in PacHarvSable
	SELECT DISTINCT CAST(H.TRIP_ID AS VARCHAR(50)) AS TRIP_ID FROM GFFOS.dbo.GF_HAIL_NUMBER H
	INNER JOIN PacHarvSable.dbo.D_Official_Catch C ON H.HAIL_NUMBER = C.HAIL_IN_NO
	WHERE H.HAIL_TYPE = 'IN'
	) H
	GROUP BY TRIP_ID
	) OL ON OL.TRIP_ID = C.TRIP_ID
WHERE OL.TRIP_ID IS NULL AND SPECIES_CODE = '044' AND YEAR(C.BEST_DATE) > 2004
	AND ISNULL(MAJOR_STAT_AREA_CODE,'00') != '01' AND ISNULL(DFO_STAT_AREA_CODE,0) != 12
	/*AND FISHERY_SECTOR != 'ROCKFISH INSIDE' AND FISHERY_SECTOR ! = 'GROUNDFISH TRAWL'*/
	AND FISHERY_SECTOR = 'GROUNDFISH TRAWL'
GROUP BY YEAR(C.BEST_DATE), C.FISHERY_SECTOR, C.TRIP_CATEGORY, C.GEAR, C.GEAR_SUBTYPE
ORDER BY FISHERY_SECTOR, CALENDAR_YEAR